### ISSUE TITLE
installing neuroshare for python3.6

### ISSUE THREAD

**Issue by Visdoom** [G-Node/python-neuroshare#27]
Hey there,
I am trying to install the neuroshare package for python3 and was wondering if you can help.
I unpacked the neuroshare-0.9.3 into my anaconda3/lib/python3.6/site-packages folder and then run `python3.6 setup.py install` . 
This is the error log of my installation
[neuroshare_errorlog.txt](https://github.com/G-Node/python-neuroshare/files/1071982/neuroshare_errorlog.txt)

`gcc` is installed on the system: 
`gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4`

I also tried just `python setup.py install` but then the python2.7 compiler is used and I can not use the package in a python3 console.
For py2.7 everything worked out fine.  

So how do I get the package to be importable into a py 3 script?

**Comment by gicmo** [comment]
I looked at the error and was totally confused because I couldn't find the `PyCObject_FromVoidPtr` function in the code. I then realized that this is already fix in the master branch but I have not done a release. Ups! Can you try [master](https://github.com/G-Node/python-neuroshare/archive/master.zip)? I will do a release soon.

**Comment by Visdoom** [comment]
Hi gicmo, 
with the master all worked fine. Thank you!

**Comment by gicmo** [comment]
Glad to hear! I will do a release shortly. Thanks for testing!
